[package]
name = "league_file"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
binrw.workspace = true
league_core.workspace = true
league_utils.workspace = true
bitflags.workspace = true
serde.workspace = true